name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - name: Obtendo o código do projeto
          uses: actions/checkout@v4
        - name: Setup dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: "8.0.300"
        - name: Execução do comando build
          working-directory: ./src
          run: dotnet build Review-Filmes.sln

  testes:
    needs: [build]
    uses: Layzan/desafio-cicd-01/.github/workflows/testes.yml@main
    secrets: inherit

  release:
      name: Criação de Release
      needs: [testes]
      runs-on: ubuntu-latest
      steps:
        - name: Obtendo o código do projeto
          uses: actions/checkout@v4
        - name: Analise do Dockerfile
          uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: ./src/Review-Filmes.Web/Dockerfile
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            context: ./src
            file: src/Review-Filmes.Web/Dockerfile
            tags: |
              layzan/projeto-devops-pro:latest
              layzan/projeto-devops-pro:v${{ github.run_number }}
        - name: Executar o Trivy
          uses: aquasecurity/trivy-action@0.28.0
          with:
            scan-type: 'image'
            image-ref: layzan/projeto-devops-pro:v${{ github.run_number }}
            format: sarif
            output: 'trivy-docker-result.sarif'
            severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        - name: Upload do arquivo Trivy para o GitHub
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: 'trivy-docker-result.sarif'